### ISSUE TITLE
Explicitly mention supported platforms in README.md

### ISSUE THREAD

**Issue by kalebo** [grisha85/umake#12]
Some mention of which platforms are supported would be useful for those investigating this project. It would also be helpful if any future support for other platforms is planned, e.g., BSDs including OSX, Windows etc. or what the blocking issues are for building on multiple platforms.

From a cursory glance at the code it looks like these issues are:
1. use of `strace`. This effectively restricts umake to running on linux right now. It might be possible to get it to run on BSDs by using `truss` or OSX's `dtruss` instead. There are several roughly equivalent utilities on windows (e.g., http://rogerorr.github.io/NtTrace/), but I haven't really evaluated them to see how good of a fit they are for this purpose. 
2. use of bash. Bazel also had to go through a similar [issue](https://github.com/bazelbuild/bazel/issues/4319)
3. assumption of UNIX file permissions.

**Comment by grisha85** [comment]
Thanks for your reply. 
1. Indeed `umake` working only on linux and I don't have any plans to support other platforms (pull requests are welcome)
2. `strace` - due to performance issues(more details: https://github.com/grisha85/umake/blob/master/doc/dpdk-build.md), I'm checking other options to instrument builds (fuse as tup using is one if them).
3. bash can be removed easilly
4. `assumption of UNIX file permissions.` - can you explain?
